# Generated by Django 4.2.5 on 2023-10-11 08:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите текст заявки', verbose_name='Текст заявки')),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Телефонный номер должен быть введен в формате: '+799999999'. Допускается не более 11 цифр.", regex='^\\+?7?\\d{10}$')])),
                ('e_mail', models.EmailField(max_length=200, unique=True, verbose_name='Электронный адрес')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviсes', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик услуги')),
                ('service', models.ForeignKey(help_text='Выберите вид услуги', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types', to='posts.service', verbose_name='Вид услуги')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
    ]
