# Generated by Django 4.2.5 on 2023-10-18 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик услуги')),
            ],
            options={
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('WT', 'Ожидание'), ('ST', 'Старт'), ('PREP', 'Интервью'), ('TZ', 'Техническое задание'), ('PRJ', 'Проект'), ('DES', 'Дезайн'), ('DEV', 'Разработка'), ('TEST', 'Тестирование'), ('STUP', 'Запуск продукта'), ('MNT', 'Техническая поддержка'), ('FN', 'Проект закрыт')], max_length=21)),
                ('description', models.TextField()),
                ('prev_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status', to='posts.status')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='e_mail',
            field=models.EmailField(max_length=200, verbose_name='Электронный адрес'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала этапа')),
                ('end_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата окончания этапа')),
                ('process_mng', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_mng', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.project')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.status')),
            ],
            options={
                'ordering': ('-project',),
            },
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.ForeignKey(help_text='Выберите заказ', on_delete=django.db.models.deletion.CASCADE, related_name='order', to='posts.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_mng',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_mng', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ManyToManyField(through='posts.Workflow', to='posts.status'),
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lt', models.F('end_date'))), name='start_date_before_end_date'),
        ),
    ]
