# Generated by Django 4.2.5 on 2023-10-18 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_project_status_alter_order_author_alter_order_e_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='prev_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status', to='posts.status'),
        ),
    ]
