# Generated by Django 4.2.5 on 2023-10-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_status_prev_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('WAIT', 'Ожидание'), ('START', 'Старт'), ('INITIAL', 'Интервью'), ('TZ', 'Техническое задание'), ('PROJECT', 'Проект'), ('DESIGN', 'Дезайн'), ('DEVELOP', 'Разработка'), ('TEST', 'Тестирование'), ('STARTUP', 'Запуск продукта'), ('MAINTAIN', 'Техническая поддержка'), ('FINISH', 'Проект закрыт')], max_length=21),
        ),
    ]
