# Generated by Django 4.2.5 on 2023-10-24 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_order_service_alter_project_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='author',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Выберите вид услуги', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types', to='posts.service'),
        ),
    ]
