# Generated by Django 4.2.5 on 2023-10-24 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_order_author_alter_order_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Телефонный номер должен быть введен в формате: '+799999999'. Допускается не более 11 цифр.", regex='^\\+?7?\\d{10}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='text',
            field=models.TextField(verbose_name='Текст заявки'),
        ),
    ]
