# Generated by Django 4.2.5 on 2023-10-25 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_order_phone_number_alter_order_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service',
        ),
    ]
